# frozen_string_literal: true

source "https://rubygems.org"

gemspec

require_relative "../../scripts/dependency_helper"
gemspec_dependencies(__dir__)

eval_gemfile(File.expand_path("../../Gemfile", __dir__))
